### ISSUE TITLE
Complete the basic README

### ISSUE THREAD

**Issue by philipp-baumann** [opengisch/talks_revealmd#8]
- Link the plugin website
- Add browser presentation modus
- After 2. git clone: add to also find existing presentations in the slide folder
- Add point 5. to contribute back
- Update YAML header
- Screenshot themes
- Publish your specified presentations (fork and github pages; optional)
- Contributor notes (Reveal.js reveal-md)

**Comment by signedav** [comment]
Opened task in clickup.

**Comment by philipp-baumann** [comment]
update table of contents, e.g. via
https://github.com/ekalinin/github-markdown-toc
